import type { NextPage } from 'next';
import Head from 'next/head';
import { Navbar } from '../components/Navbar';

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="container mx-auto">
        <Navbar />
        <main>
          <h1>Hello Auction House</h1>
        </main>
      </div>
    </>
  );
};

export default Home;
