import type { NextPage } from 'next';
import Head from 'next/head';
import { AuctionCard } from '../components/AuctionCard';
import { CreateAuctionForm } from '../components/CreateAuctionForm';
import { Loader } from '../components/Loader';
import { Navbar } from '../components/Navbar';
import { useGetAuctionsListQuery } from '../graphql/gen';

const Home: NextPage = () => {
  const { data: auctionLists, loading, error } = useGetAuctionsListQuery();
  return (
    <>
      <Head>
        <title>🏠 Auction House</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="container mx-auto">
        <Navbar />
        <main className="mt-4">
          <div className="grid grid-cols-12 my-5">
            <div className="col-span-8">
              <div className="flex flex-wrap gap-4">
                {loading ? (
                  <Loader />
                ) : error ? (
                  <p>{error.message}</p>
                ) : (
                  auctionLists?.getAuctionsList.map((a) => (
                    <AuctionCard auction={a} key={a.id} />
                  ))
                )}
              </div>
            </div>
            <div className="col-span-4 relative">
              <CreateAuctionForm />
            </div>
          </div>
        </main>
      </div>
    </>
  );
};

export default Home;
